[tool.poetry]
name = "cashflow"
version = "2.0"
description = "Django project to manage receipts and reimbursements at Datasektionen"
# TODO: Fix authors and maintainers (?)
authors = [
	"Ture Teknolog"
]

[tool.poetry.dependencies]
python = "^3.6"
django = "1.11.15"
requests = "2.13.0"
psycopg2 = "2.7.5"
djangorestframework = "3.6.2"
django-cors-headers = "2.4.0"
gunicorn = "19.9.0"
django-widget-tweaks = "1.4.2"
dj-database-url = "0.5.0"
whitenoise = "3.3.1"
django-queued-storage = "0.8.0"
django-storages = "1.6.6"
boto = "2.49.0"
raven = "*"
celery = "4.2.1"
pi-heif = "0.9.0"
pillow = "8.4.0"
authlib = "0.15.6"

[tool.poetry.dev-dependencies]
django-extensions = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
