[project]
name = "cashflow"
version = "2.0"
description = ""
authors = [
	{name = "Alexander Viklund", email = "viklu@kth.se"},
	{name = "Mauritz Zachrisson", email="mauritzz@kth.se"}
]
package-mode = false
readme = "README.md"
requires-python = "==3.14.2"
dependencies = [
    "django (>=6.0.1,<7.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "psycopg2 (>=2.9.11,<3.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "django-widget-tweaks (==1.4.2)",
    "dj-database-url (==0.5.0)",
    "whitenoise (>=4,<5)",
    "django-storages (==1.14.6)",
    "boto3 (==1.42.30)",
    "raven",
    "celery (==4.2.1)",
    "pi-heif (==0.9.0)",
    "pillow (>=12.1.0,<13.0.0)",
    "authlib (==0.15.6)",
    "legacy-cgi (>=2.6.4,<3.0.0)",
    "setuptools (>=80.9.0,<81.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "django-extensions"
]
